# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import oscar.models.fields.slugfield


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20160623_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='slug',
            field=models.CharField(default='', max_length=50, unique=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=oscar.models.fields.slugfield.SlugField(max_length=255, verbose_name='Slug'),
        ),
    ]
